version: "3.8"

services:
  opencode-dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HOST_UID: ${UID:-1000}
        HOST_GID: ${GID:-1000}
    container_name: opencode-dev

    # Map host UID/GID 1:1 into the container for bind mounts
    userns: keep-id
    user: "${UID:-1000}:${GID:-1000}"

    # Security: Read-only root filesystem where possible
    read_only: false # Set to true if your app doesn't write to filesystem

    # Security: Drop all capabilities, add only what's needed
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID

    # Security: Prevent privilege escalation
    security_opt:
      - no-new-privileges:true

    # Resource limits for security/stability
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: "2.0"
        reservations:
          memory: 512M
          cpus: "0.5"

    # Network configuration
    ports:
      - "4000:4000" # TUI client connection (unchanged)
      # Note: tunnel ports are internal only, no host exposure needed

    # Podman secrets (more secure than environment variables)
    secrets:
      - cloudflare_tunnel_token

    # Environment variables
    environment:
      - NODE_ENV=development
      - HOSTNAME=0.0.0.0
      - PORT=4000
      # Secret file path will be available at /run/secrets/cloudflare_tunnel_token
      - CLOUDFLARE_TUNNEL_TOKEN_FILE=/run/secrets/cloudflare_tunnel_token
      # Add your specific environment variables

# Define secrets at the compose file level
secrets:
  cloudflare_tunnel_token:
    external: true

    # Volume mounts with security considerations
    volumes:
      # Source code (bind mount)
      # Use a btrfs subvolume for the workspace for snapshot-friendly dev
      # Change this path if your subvolume differs
      - ${OPENCODE_SUBVOL:-/home/jm/data/code/opencode_subvol}:/workspace:Z

      # Neovim configuration (optional)
      - type: bind
        source: ${HOME}/.config/nvim
        target: /home/opencode/.config/nvim:Z,ro
        read_only: true
        bind:
          propagation: rprivate

      # Node modules cache (named volume for better performance)
      - node_modules_cache:/workspace/node_modules

      # Secure credentials directory (read-only)
      - type: bind
        source: ${HOME}/.opencode/credentials
        target: /home/opencode/.credentials:Z,ro
        read_only: true
        bind:
          propagation: rprivate

      # Temporary directory (tmpfs for security)
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 100M
          mode: 1777

    # Working directory
    working_dir: /workspace

    # Keep container running for development
    tty: true
    stdin_open: true

    # Restart policy
    restart: unless-stopped

    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    # Custom DNS (optional, for security)
    dns:
      - 1.1.1.1
      - 8.8.8.8

    # Hostname for container
    hostname: opencode-dev

# Named volumes
volumes:
  node_modules_cache:
    driver: local
  bun_cache:
    driver: local

# Custom network (optional, for isolation)
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
