package: opencode
generate:
  - types
output: types.gen.go
types:
  skip:
    - ConfigShare
    - Agent
    - AgentPart
    - App
    - AssistantMessage
    - Command
    - Config
    - AppLogJSONRequestBody
    - AppLogJSONBodyLevel
    - Error
    - MessageAbortedError
    - ProviderAuthError
    - UnknownError
    - FilePart
    - FileSource
    - ReasoningPart
    - Session
    - TextPart
    - ToolPart
    - UserMessage
    - Message
    - Part
    - Permission
    - SnapshotPart
    - StepFinishPart
    - StepStartPart
    - SymbolSource
    - ToolStateCompleted
    - ToolStateError
    - ToolStatePending
    - ToolStateRunning
    - FilePartSource
    - FilePartSourceText
    - McpLocalConfig
    - McpRemoteConfig
