// Code generated by ogen, DO NOT EDIT.

package api

// AuthSetParams is parameters of auth.set operation.
type AuthSetParams struct {
	ID string
}

// FileReadParams is parameters of file.read operation.
type FileReadParams struct {
	Path string
}

// FindFilesParams is parameters of find.files operation.
type FindFilesParams struct {
	Query string
}

// FindSymbolsParams is parameters of find.symbols operation.
type FindSymbolsParams struct {
	Query string
}

// FindTextParams is parameters of find.text operation.
type FindTextParams struct {
	Pattern string
}

// PostSessionByIdPermissionsByPermissionIDParams is parameters of postSessionByIdPermissionsByPermissionID operation.
type PostSessionByIdPermissionsByPermissionIDParams struct {
	ID           string
	PermissionID string
}

// SessionAbortParams is parameters of session.abort operation.
type SessionAbortParams struct {
	ID string
}

// SessionChatParams is parameters of session.chat operation.
type SessionChatParams struct {
	ID string
}

// SessionChildrenParams is parameters of session.children operation.
type SessionChildrenParams struct {
	ID string
}

// SessionCommandParams is parameters of session.command operation.
type SessionCommandParams struct {
	ID string
}

// SessionDeleteParams is parameters of session.delete operation.
type SessionDeleteParams struct {
	ID string
}

// SessionGetParams is parameters of session.get operation.
type SessionGetParams struct {
	ID string
}

// SessionInitParams is parameters of session.init operation.
type SessionInitParams struct {
	ID string
}

// SessionMessageParams is parameters of session.message operation.
type SessionMessageParams struct {
	ID        string
	MessageID string
}

// SessionMessagesParams is parameters of session.messages operation.
type SessionMessagesParams struct {
	ID string
}

// SessionRevertParams is parameters of session.revert operation.
type SessionRevertParams struct {
	ID string
}

// SessionShareParams is parameters of session.share operation.
type SessionShareParams struct {
	ID string
}

// SessionShellParams is parameters of session.shell operation.
type SessionShellParams struct {
	ID string
}

// SessionSummarizeParams is parameters of session.summarize operation.
type SessionSummarizeParams struct {
	ID string
}

// SessionUnrevertParams is parameters of session.unrevert operation.
type SessionUnrevertParams struct {
	ID string
}

// SessionUnshareParams is parameters of session.unshare operation.
type SessionUnshareParams struct {
	ID string
}

// SessionUpdateParams is parameters of session.update operation.
type SessionUpdateParams struct {
	ID string
}
