components:
  schemas:
    Provider:
      type: object
      required: [id, name]
      properties:
        id:
          type: string
          format: uuid  # Ogen gen's uuid.UUID
        name:
          type: string
        description:
          type: string
          nullable: true  # Ogen gen's NilString
        models:  # Array example
          type: array
          items:
            $ref: '#/components/schemas/Model'
      x-oapi-codegen-extra-tags:  # Custom tags
        valid: "structonly"
    Model:
      type: object
      required: [id, name]
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        provider:
          $ref: '#/components/schemas/Provider'  # Ref to other schema
    Agent:
      type: object
      properties:
        name:
          type: string
        mode:
          type: string
          enum: [primary, secondary]  # Ogen gen's enum type
        description:
          type: string
          nullable: true
    Event:
      oneOf:  # Ogen gen's sum type
        - $ref: '#/components/schemas/EventInstallationUpdated'
        - $ref: '#/components/schemas/EventSessionUpdated'
        - $ref: '#/components/schemas/EventMessagePartUpdated'
        # Add all variants from legacy script (e.g., from oneOf refs)
      discriminator:  # Enables tagged union
        propertyName: type
        mapping:  # Optional: Explicit mapping for inference
          installation.updated: '#/components/schemas/EventInstallationUpdated'
          session.updated: '#/components/schemas/EventSessionUpdated'
          message.part.updated: '#/components/schemas/EventMessagePartUpdated'
      x-ogen-name: Event  # Ensures clean naming
    EventInstallationUpdated:  # Example variant schema
      type: object
      properties:
        type:
          type: string
          enum: [installation.updated]  # Discriminator value
        properties:  # From spec
          version:
            type: string
      required: [type, properties]
      x-oapi-codegen-extra-tags:
        json: "-,omitempty"  # Custom tag for internals
    # Repeat for other variants (e.g., EventSessionUpdated with Session ref)
    EventSessionUpdated:
      type: object
      properties:
        type:
          type: string
          enum: [session.updated]
        info:
          $ref: '#/components/schemas/Session'
    EventMessagePartUpdated:
      type: object
      properties:
        type:
          type: string
          enum: [message.part.updated]
        properties:
          part:
            $ref: '#/components/schemas/Part'  # Union ref

